name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:
  label-gate:
    uses: AustralianCancerDataNetwork/cava-devops/.github/workflows/label-gate.yml@main
  build-test:
    uses: AustralianCancerDataNetwork/cava-devops/.github/workflows/build-test-postgres.yml@6f809e58cf9c556a1935d64f620b89b714950247
    # uses: AustralianCancerDataNetwork/cava-devops/.github/workflows/build-test-postgres.yml@main
    with:
      postgres-db: orm_loader_test
      setup-commands: |
        uv run omop-config configure orm_loader \
          --set test_orm_db.kind=cdm \
          --set test_orm_db.connection.dialect=postgresql+psycopg \
          --set test_orm_db.connection.host=localhost \
          --set test_orm_db.connection.port=5432 \
          --set test_orm_db.connection.user=test \
          --set test_orm_db.connection.password=test \
          --set test_orm_db.connection.database_name=orm_loader_test \
          --set test_orm_db.connection.test_only=true \
          --set test_orm_db.schema_name=public
